DELETE FROM LIBRARY.ROLE_ENTITY r WHERE r.ROLE in ('STAFF', 'ADMIN','LIBRARIAN');
insert into LIBRARY.ROLE_ENTITY r (r.ROLE) values ('STAFF');
insert into LIBRARY.ROLE_ENTITY r (r.ROLE) values ('ADMIN');
insert into LIBRARY.ROLE_ENTITY r (r.ROLE) values ('LIBRARIAN');
