DELETE FROM LIBRARY_SYSTEM.ROLE_ENTITY r WHERE r.ROLE in ('STAFF', 'ADMIN','LIBRARIAN');
insert into LIBRARY_SYSTEM.ROLE_ENTITY r (r.ROLE) values ('STAFF');
insert into LIBRARY_SYSTEM.ROLE_ENTITY r (r.ROLE) values ('ADMIN');
insert into LIBRARY_SYSTEM.ROLE_ENTITY r (r.ROLE) values ('LIBRARIAN');
