ALTER TABLE LIBRARY_SYSTEM.category DROP CONSTRAINT fk_category_parent;

ALTER TABLE LIBRARY_SYSTEM.category ADD CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES LIBRARY_SYSTEM.category(id) ON DELETE SET NULL;
