DELETE FROM LIBRARY_SYSTEM.USER_SYSTEM_ROLES u_r WHERE u_r.USER_ID =1;
DELETE FROM LIBRARY_SYSTEM.USER_SYSTEM u WHERE u.ID =1;
INSERT INTO LIBRARY_SYSTEM.USER_SYSTEM
(ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, EMAIL, ENABLED, FULL_NAME, PASSWORD, USERNAME)
VALUES(1,NULL, NULL, NULL,NULL, 'taheraminAdmin@gmail.com', 1, 'taher admin', '$2a$10$KWypEpGsmqI4PbNzy2ET5evZJyJpQug951WKMVysrswGzlPARJZ8G', 'admin admin');

INSERT INTO LIBRARY_SYSTEM.USER_SYSTEM_ROLES (USER_ID,ROLE_ID) VALUES (1,2);